### ISSUE TITLE
Feature request: add support for WORKDIR instruction in Vib

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/Vib#38]
It would be nice to have Docker's WORKDIR instruction to specify the current working directory implement in Vib to be used with a recipe. This would be useful to be used in between modules/stages for complex applications i.e webapps, etc.

**Ref**. https://docs.docker.com/reference/dockerfile/#workdir

**Comment by kbdharun** [comment]
Having this option would be useful in cases like https://github.com/Vanilla-OS/chronos-frontend/pull/62, where I had to `cd` to the app directory in the ENTRYPOINT instruction to prevent a restart loop caused by missing package files in the root directory.

**Comment by lambdaclan** [comment]
Hello there. 

I would like to work on this task. I have a preliminary but working **draft** pull request available:

https://github.com/Vanilla-OS/Vib/pull/57

A lot of things require discussion and input from the upstream developers so let us carry on after the initial review.

Thank you!
