### ISSUE TITLE
Support for user configuration

### ISSUE THREAD

**Issue by arejula27** [Vanilla-OS/Vib#48]
Is there any module that allows to preconfigure the image? I mean cloning dotfiles, installing apps at the user lvl, etc.

IDK if it should be done in the docker file generated (USER) or after the first boot.

**Comment by taukakao** [comment]
Vib is just a Containerfile builder, so I don't know what you mean with user configuration.

If you want to create your own image based on another image using vib, you can use https://github.com/vanilla-OS/custom-image

**Comment by arejula27** [comment]
I mean something for modifying the `/etc/skel` folder, however maybe this is already possible by just adding the files. This issue could be closed so new users start with some config

**Comment by taukakao** [comment]
Oh VanillaOS, you can edit /etc/skel with `host-shell pkexec`
But you can also just put the files into includes.container/etc/skel/ in your vib path and it should add it to the image
