### ISSUE TITLE
Use apt-get instead of apt

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/Vib#50]
Using `apt` CLI in scripts leads to this warning:
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

From `apt`'s manpage:
> apt provides a high-level commandline interface for the package management system. It is intended as an end user interface and enables some options better suited for interactive usage by default compared to more specialized APT tools like [apt-get(8)](https://manpages.debian.org/bookworm/apt/apt-get.8.en.html) and [apt-cache(8)](https://manpages.debian.org/bookworm/apt/apt-cache.8.en.html).

So Vib should use stable `apt-get` CLI instead of `apt`

**Comment by lambdaclan** [comment]
Hello there. I would like to work on this task. I have created a preliminary pull request https://github.com/Vanilla-OS/Vib/pull/51 for your review. I will be happy to do any adjustments if at all necessary, so please let me know. Thank you.
