### ISSUE TITLE
cmd: Building a container image without a recipe name throws error

### ISSUE THREAD

**Issue by deepu9** [Vanilla-OS/Vib#53]
**Bug**
Running `vib build` without a recipe name throws index out of range error.

**Steps to reproduce**
1. Create a recipe file in a folder.
2. Run `vib build`

![Selection_001](https://github.com/Vanilla-OS/Vib/assets/3803259/cf87a367-36ec-478c-b647-ef83fe8731a2)

**Comment by deepu9** [comment]
Thanks @kbdharun for fixing the typo.

Can I work on it?

**Comment by kbdharun** [comment]
> Thanks @kbdharun for fixing the typo.
> 
> Can I work on it?

Sure, currently you won't get this error if the file is named `recipe.yml`, `recipe.yaml`, `vib.yml` and `vib.yaml`. I would suggest printing an Error that a filename should be passed (in your case, and the string shouldn't be empty unless it is named recipe or vib).

**Comment by deepu9** [comment]
@kbdharun I did follow **Getting Started** article and created `vib.yml` file in a folder.

So, you are suggesting to print an error that the filename is required, correct me if I'm wrong.

The existing code allows the user to run the build command without a recipe name. If you don't pass the recipe name, then the code will check whether `recipe.yml` or `recipe.yaml` or `vib.yaml` or `vib.yml` exists in the folder the user is running the command. If none of the file exists, then it will throw an error saying **missing recipe path**

Do you want me to replace the above logic with printing an error when the filename isn't provided?

**Comment by deepu9** [comment]
I've created the Draft PR to get some feedback on the updates. Can anyone review it and let me know of any feedback. Thanks

**Comment by kbdharun** [comment]
> Do you want me to replace the above logic with printing an error when the filename isn't provided?

Nope, you can print an error like "A valid recipe file can't be found in the current directory, specify the recipe's custom filename with the command"
