### ISSUE TITLE
Vib doc search bar auto-suggest triggers a blank page when there is no suggestion

### ISSUE THREAD

**Issue by lusinge** [Vanilla-OS/Vib#69]
Hello guys 👋

When you search for something on vib's documentation website, the auto-suggest will break the whole website if there's no suitable suggestion. The whole page goes blank :
![See here](https://github.com/user-attachments/assets/1629e1d8-bf03-4f42-9df2-6b800f42a5e5)

**Comment by kbdharun** [comment]
Hi, thanks for the issue. This issue was fixed upstream in Chronos frontend, our production version will be updated soon.
