### ISSUE TITLE
Proposal: add Fonts module

### ISSUE THREAD

**Issue by arejula27** [Vanilla-OS/Vib#71]
As vib is intended for being a tool for building a os and not only a abstraction over docker file I suggest adding one of the most common things to do in a system, add a module for specifying fonts and it will automatically download, following the blue build module we can add support for Google fonts and need fonts also. This module will download and install the fonts. The user should only write the name of the font or the URL.

**Comment by arejula27** [comment]
If you like the idea I can work on it, it should not be really difficult

**Comment by taukakao** [comment]
Isn't installing a font just downloading the file and placing it in `/usr/local/share/fonts`?

If yes, then I don't think it's worth adding complexity to Vib, since it could already be done quite easily.

**Comment by arejula27** [comment]
That's a good point, however I feel that this tools avoid the technical overhead and let users configure the system in a descriptive way without technical knowledge required.

For me it is trivial how to do it, however it requires knowing where fonts are allocated and scripting knowledge. Installing multiple fonts can produce a complex script.

I feel that having a simple interface as this example will be beneficial for the project 
https://blue-build.org/reference/modules/fonts/

If you do not agree just close the issue.

**Comment by arejula27** [comment]
When I say module I meant plugin, mb

**Comment by taukakao** [comment]
non-technical users can already install fonts by putting them in `~/.local/share/fonts` or by double clicking them on most desktop environments. 

Also, non-technical users are not the target audience for vib.

**Comment by taukakao** [comment]
I don't mean to dismiss this issue. I'm thankful for your imput. 
I just think maintaining this feature is not worth the effort in this szenario.
